### ISSUE TITLE
Error when launching app via "open with" the second time

### ISSUE THREAD

**Issue by paulgreg** [paulgreg/rsstodolist-native#1]
Step to reproduce : 
- After install rsstodolist app on your phone, 
- open twitter or a browser (an application containing links),
- click on a link and, in the selection menu, chose "open with rsstodolist",
- rsstodolistnative opens
- without closing the rsstodolist app, switch back to original app (twitter or browser or else),
- click on a second link and chose again "open with rsstodolist",
- an error occurs while opening rsstodolistnative with following error :

![rsstodolistnative](https://cloud.githubusercontent.com/assets/250740/12385189/a231393a-bdb9-11e5-9bcc-20ac8e5406fc.png)

**Comment by hshristov** [comment]
@paulgreg Could you please share the application so that we can investigate this?

**Comment by paulgreg** [comment]
I’m sorry I’m not sure I understood. 
Do you want the APK ?
If so, I can upload it tonight.
Otherwise, the code is on that repo (https://github.com/paulgreg/rsstodolist-native).
Just clone the repo, copy app/config.json.dist to app/config.json and run it with tns run android.

**Comment by paulgreg** [comment]
@hshristov Here’s an APK built from https://github.com/paulgreg/rsstodolist-native sources : 
[rsstodolistnative-debug.apk.zip](https://github.com/paulgreg/rsstodolist-native/files/94793/rsstodolistnative-debug.apk.zip)

**Comment by hshristov** [comment]
@paulgreg thanks. Will check it out.

**Comment by hshristov** [comment]
Hi @paulgreg,
I've refatored our Frame class so it won't crash with 1.6.0 but I'm not sure what scenario you want to cover. Could you elaborate more on what you need to do?

**Comment by paulgreg** [comment]
Thanks @hshristov.
I’ll try to recompile and install the application with version 1.6.0 to see if bug has disappeared.
About the scenario, I’m just trying to open my application a second time and would like to avoid a crash the second time I open it. I updated the steps to reproduce in issue description.

**Comment by paulgreg** [comment]
I do not reproduce the problem anymore since migration to nativescript 1.7.
